### ISSUE TITLE
Quite often, bsa is not woking

### ISSUE THREAD

**Issue by markusC64** [Edilbert/BSA#5]
The reason should be line 3332:

Src = MallocOrDie(strlen(argv[ic] + 4 + 1));

I guess you mean

Src = MallocOrDie(strlen(argv[ic]) + 4 + 1);

With this fix, BSA is working much better on windows.

**Comment by Edilbert** [comment]
fixed

**Comment by Edilbert** [comment]
Danke Markus für diesen Hinweis.
Viele Grüße,
Edilbert

**Comment by markusC64** [comment]
Gerne.

Mit dieser Korrektur ist BSA übrigens "valgind clean" - in der Tat hat "valgrind" unter Linux die Stelle des Fehlers gefunden.
