### ISSUE TITLE
strncasecmp / strcasecmp "non standard"

### ISSUE THREAD

**Issue by AnselmD** [Edilbert/BSA#6]
hi, 

i am trying to compile BSA for windows (using Pelles C development kit for Desktop Windows (it is free)).

I have trouble because  of strncasecmp / strcasecmp. 

Doing a quick research, it is said, they are defined in the libc standard library in BSD/POSIX but they are "non standard" (ansi c?).

I was able to compile it with

#ifdef _WIN32
#define strcasecmp _stricmp
#define strncasecmp _strnicmp
#endif

Just found a compile option "Define compatibility names" which also works. If someone is interesting, screenshot:

![2019-07-20 07_35_50-bsa project options  Release  - Win32 Console program (EXE)](https://user-images.githubusercontent.com/6770907/61574538-759acc80-aac1-11e9-9f27-a8bc022b816b.png)

**Comment by Edilbert** [comment]
Thanks for the hint.
I solved this by adding these function to the source code:
Strcasecmp
Strncasecmp
